"""Generate `src/sft/skill/REFERENCE.md` from the live Typer CLI.

Run manually with `python scripts/build_skill_reference.py`, or via the
hatch build hook (configured in `pyproject.toml`) which regenerates the
file at wheel build time so the shipped skill never drifts from the CLI.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import click  # noqa: E402
import typer  # noqa: E402


def _format_param(param: click.Parameter) -> str:
    """Render a Click parameter as a single markdown bullet."""
    if isinstance(param, click.Argument):
        name = param.human_readable_name or param.name or ""
        required = "required" if param.required else "optional"
        if param.nargs != 1:
            arity = " (repeatable)" if param.nargs == -1 else f" (×{param.nargs})"
        else:
            arity = ""
        return f"- `{name}` — argument, {required}{arity}"
    if isinstance(param, click.Option):
        opts = "/".join(f"`{o}`" for o in param.opts)
        help_text = (param.help or "").strip().replace("\n", " ")
        flag_kind = "flag" if param.is_flag else "option"
        if param.required:
            flag_kind += ", required"
        if help_text:
            return f"- {opts} — {flag_kind}. {help_text}"
        return f"- {opts} — {flag_kind}."
    return f"- `{param.name}`"


def _walk(
    cmd: click.Command, ctx: click.Context, path: list[str], lines: list[str]
) -> None:
    """Depth-first walk; emit a section per leaf command."""
    if isinstance(cmd, click.Group):
        for name in sorted(cmd.commands):
            sub = cmd.commands[name]
            if getattr(sub, "hidden", False):
                continue
            sub_ctx = click.Context(sub, info_name=name, parent=ctx)
            _walk(sub, sub_ctx, [*path, name], lines)
        return

    invocation = " ".join(["sft", *path])
    help_text = (cmd.help or cmd.short_help or "").strip()

    lines.append(f"## `{invocation}`")
    lines.append("")
    if help_text:
        for paragraph in help_text.split("\n\n"):
            lines.append(paragraph.strip())
            lines.append("")

    params = [p for p in cmd.params if not getattr(p, "hidden", False)]
    if params:
        lines.append("**Parameters:**")
        lines.append("")
        for p in params:
            lines.append(_format_param(p))
        lines.append("")

    json_flag = any(
        isinstance(p, click.Option) and "--json" in p.opts for p in cmd.params
    )
    if json_flag:
        lines.append("Supports `--json` (use this when parsing the output).")
        lines.append("")


def generate() -> str:
    """Generate the reference markdown body."""
    from sft.cli import app  # noqa: WPS433 — local import after sys.path setup

    click_cmd = typer.main.get_command(app)
    ctx = click.Context(click_cmd, info_name="sft")

    body: list[str] = [
        "<!-- This file is auto-generated by scripts/build_skill_reference.py. Do not edit by hand. -->",
        "<!-- Regenerate locally with: `python scripts/build_skill_reference.py`. -->",
        "",
        "# sft command reference",
        "",
        "Authoritative list of every (non-hidden) `sft` command and its flags.",
        "Every read-side command supports `--json`; agents should always pass it when output will be parsed.",
        "",
    ]
    _walk(click_cmd, ctx, [], body)
    return "\n".join(body).rstrip() + "\n"


def main(output_path: Path | None = None) -> Path:
    out = output_path or REPO_ROOT / "src" / "sft" / "skill" / "REFERENCE.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate())
    return out


if __name__ == "__main__":
    written = main()
    print(f"Wrote {written}")
